#!/usr/bin/env bash

set -e

# reset dist
rm -rf dist
mkdir -p dist

# use babel directly to create the ES module version
babel \
  src/index.js \
  -o dist/babelrc-rollup.mjs

# test our rollup build with the babel-built version
npm run build

# test our rollup build again with the rollup-built version
npm run build
